import {
  CREATE_BOOK_OK,
  CREATE_BOOK_FAILED,
  GET_BOOKS_OK,
  GET_BOOKS_FAILED,
  DELETE_BOOK_OK,
  SET_UPDATE_BOOK,
  PREPARE_TO_UPDATE,
  UPDATE_BOOK_OK,
  UPDATE_BOOK_FAILED,
} from "../actionTypes";
